name: Rust

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 15 */2 *'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2.7.5
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check PR Formatting # Warn about formatting in PRs if needed
      if: github.event_name == 'pull_request'
      uses: mbrobbel/rustfmt-check@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        mode: review
    - name: Clear cache # clear cache every other month (https://github.com/Swatinem/rust-cache/issues/181)
      if: github.event_name =='schedule'
      run: |
        cargo clean
        rm -rf ~/.cargo/registry
        rm -rf ~/.cargo/git

